openapi: 3.0.3
info:
  title: Antiplagiarism Gateway API
  description: API Gateway for Antiplagiarism System
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
    description: Local development server
tags:
  - name: Works
    description: Operations with student works
  - name: Files
    description: File operations (proxy to storage service)
  - name: Reports
    description: Report operations (proxy to analysis service)
paths:
  /works:
    post:
      tags: [Works]
      summary: Submit a new work for analysis
      operationId: submitWork
      description: |
        Proxy for submitting a work file.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required: [student_id, assignment_id, file]
              properties:
                student_id:
                  type: string
                  description: Student identifier
                  example: "student_123"
                assignment_id:
                  type: string
                  description: Assignment identifier
                  example: "kpo_lab3_2024"
                file:
                  type: string
                  format: binary
                  description: File to upload and analyze
      responses:
        '200':
          description: Work submitted and analyzed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkSubmissionResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '413':
          description: File too large
        '500':
          $ref: '#/components/responses/InternalServerError'

  /works/{work_id}/reports:
    get:
      tags: [Reports]
      summary: Get all reports for a work
      operationId: getWorkReports
      parameters:
        - name: work_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of reports for the work
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Report'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /files/{file_id}:
    get:
      tags: [Files]
      summary: Download a file
      operationId: downloadFile
      parameters:
        - name: file_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: File content
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          $ref: '#/components/responses/NotFound'
  
  /health:
    get:
      summary: Health check
      operationId: healthCheck
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "OK"
                  gateway:
                    type: string
                    enum: [healthy, unhealthy]
                  file_storage:
                    type: string
                    enum: [healthy, unhealthy]
                  file_analysis:
                    type: string
                    enum: [healthy, unhealthy]

components:
  schemas:
    WorkSubmissionResponse:
      type: object
      properties:
        work_id:
          type: string
          description: Unique work identifier
          example: "work_kpo_lab3_ivanov_1733390000"
        file_id:
          type: string
          description: Uploaded file identifier
          example: "file_abc123.pdf"
        submitted_at:
          type: string
          format: date-time
          example: "2024-12-05T10:30:00Z"

    Report:
      type: object
      properties:
        report_id:
          type: string
        work_id:
          type: string
        file_id:
          type: string
        student_id:
          type: string
        assignment_id:
          type: string
        plagiarism_score:
          type: number
          format: float
          minimum: 0
          maximum: 100
          description: Percentage of plagiarism detected (0-100)
        is_plagiarism:
          type: boolean
          description: True if plagiarism detected
        similar_works:
          type: array
          items:
            $ref: '#/components/schemas/SimilarWork'
          description: List of similar works found
        word_count:
          type: integer
          minimum: 0
        analysis_duration_ms:
          type: integer
          minimum: 0
        status:
          type: string
          enum: [completed, failed]
          default: completed
        error_message:
          type: string
          description: Error message if status is failed
        created_at:
          type: string
          format: date-time

    SimilarWork:
      type: object
      properties:
        work_id:
          type: string
          example: "work_kpo_lab3_petrov_1733389260"
        student_id:
          type: string
          example: "student_456"
        similarity_percentage:
          type: number
          format: float
          minimum: 0
          maximum: 100
          example: 85.5
    ApiError:
      type: object
      properties:
        error:
          type: string
          enum: [validation_error, not_found, internal_error, service_unavailable]
          example: "validation_error"
        message:
          type: string
          example: "Missing required field: student_id"
        details:
          type: object
          additionalProperties: true
        timestamp:
          type: string
          format: date-time
          example: "2024-12-05T10:30:00Z"

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
    ServiceUnavailable:
      description: One of the microservices is unavailable
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'